name: Envoy-Demo-App-Service
services:
  app-service:
    container_name: app-service
    image: docker.io/maxence2997/envoy-demo:app-latest
    ports:
      - "8082:8082" # HTTP server port
      - "9090:9090" # Grpc server port
    environment:
      # host.docker.internal, adjust according to your host machine's IP address
      SPRING_CLOUD_CONSUL_HOST: host.docker.internal
      CONSUL_REGISTER_HOSTNAME: host.docker.internal