name: Envoy-Demo-Auth-Service
services:
  auth-service:
    container_name: auth-service
    image: docker.io/maxence2997/envoy-demo:auth-latest
    ports:
      - "8080:8080"  # HTTP server port
      - "9100:9100"  # gRPC server port
    environment:
      # host.docker.internal, adjust according to your host machine's IP address
      SPRING_CLOUD_CONSUL_HOST: host.docker.internal
      CONSUL_REGISTER_HOSTNAME: host.docker.internal
      REDIS_ADDRESS: redis://host.docker.internal:6379
