name: Envoy-Demo
services:
  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports: # 可以省略，服務可透透過 docker-compose 內部網路互相連接
      - "6379:6379"
    volumes:
      - redis-data:/data

  authservice:
    container_name: authservice
    image: docker.io/maxence2997/envoy-demo:authservice-latest
    environment:
      - REDIS_ADDRESS=redis://redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - redis

  appservice:
    container_name: appservice
    image: docker.io/maxence2997/envoy-demo:appservice-latest
    ports:
      - "8081:8081"


volumes:
  redis-data: