name: Envoy-Demo
services:
  envoy-gateway:
    image: envoyproxy/envoy:v1.34-latest
    container_name: envoy-gateway
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "10000:10000"   # export HTTP Gateway
      - "10001:10001"   # export WebSocket Gateway
      - "10002:10002"   # export TCP Gateway
      - "9901:9901"     # Envoy Admin GUI
    networks:
      - envoy-net
  redis:
    image: redis:7.0-alpine
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - envoy-net

  auth-service:
    container_name: auth-service
    image: docker.io/maxence2997/envoy-demo:authservice-latest
    environment:
      - REDIS_ADDRESS=redis://redis:6379
    ports:
      - "8080:8080"  # HTTP server port
      - "9100:9100"  # gRPC server port
    depends_on:
      - redis
    networks:
      - envoy-net

  app-service:
    container_name: app-service
    image: docker.io/maxence2997/envoy-demo:appservice-latest
    ports:
      - "8081:8081" # HTTP server port
      - "9090:9090" # Socket.io server port
    networks:
      - envoy-net

  prometheus:
    image: prom/prometheus:v3.3.1
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9999:9090"
    networks:
      - envoy-net

  grafana:
    image: grafana/grafana:12.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=a12345678
    depends_on:
      - prometheus
    networks:
      - envoy-net

volumes:
  redis-data:

networks:
  envoy-net: