name: Envoy-Demo
services:
  envoy-gateway:
    image: envoyproxy/envoy:v1.34-latest
    container_name: envoy-gateway
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "10000:10000"   # 對外開放 HTTP Gateway
      - "9901:9901"     # Envoy 管理介面
    networks:
      - envoy-net
  redis:
    image: redis:7.0-alpine
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - envoy-net

  auth-service:
    container_name: auth-service
    image: docker.io/maxence2997/envoy-demo:authservice-latest
    environment:
      - REDIS_ADDRESS=redis://redis:6379
    ports:
      - "8080:8080"  # HTTP server port
      - "9100:9100"  # gRPC server port
    depends_on:
      - redis
    networks:
      - envoy-net

  app-service:
    container_name: app-service
    image: docker.io/maxence2997/envoy-demo:appservice-latest
    ports:
      - "8081:8081" # HTTP server port
      - "9090:9090" # Socket.io server port
    networks:
      - envoy-net

volumes:
  redis-data:

networks:
  envoy-net: