name: Envoy-Demo-Envoy-Gateway
services:
  envoy-gateway:
    image: envoyproxy/envoy:v1.34-latest
    container_name: envoy-gateway
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./envoy/config:/etc/envoy/config:ro
    ports:
      - "10000:10000"   # HTTP Gateway
      - "10002:10002"   # TCP Gateway
      - "9901:9901"     # Envoy Admin GUI
    depends_on:
      - dnsmasq
    dns:
      - 172.28.0.10  # 指向 dnsmasq container
    networks:
      envoy-net:
        ipv4_address: 172.28.0.11

  dnsmasq:
    image: andyshinn/dnsmasq:2.85
    container_name: dnsmasq
    command: [
      "-k",
      "--log-facility=-",
      "--server=/consul/host.docker.internal#8600"
    ]
    networks:
      envoy-net:
        ipv4_address: 172.28.0.10

networks:
  envoy-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16