name: Envoy-Demo-Envoy-Gateway
services:
  envoy-gateway:
    image: envoyproxy/envoy:v1.34-latest
    container_name: envoy-gateway
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./envoy/config:/etc/envoy/config:ro
    ports:
      - "10000:10000"   # HTTP Gateway
      - "10002:10002"   # TCP Gateway
      - "9901:9901"     # Envoy Admin GUI
    depends_on:
      - coredns
    dns:
      - 172.28.0.10  # 指向 coreDNS container
    networks:
      envoy-net:
        ipv4_address: 172.28.0.11

  coredns:
    image: coredns/coredns:1.12.2
    container_name: coredns
    volumes:
      - ./coredns/Corefile:/Corefile
    command: -conf /Corefile
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      envoy-net:
        ipv4_address: 172.28.0.10

networks:
  envoy-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16