name: Envoy-Demo-Redis
services:
  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"  # Redis server port
    volumes:
      - redis-data:/data

volumes:
  redis-data: