# /etc/envoy/config/listeners/listeners.yaml
version_info: "1"
resources:
  - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
    name: http_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
      - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http

              rds:
                config_source:
                  resource_api_version: V3
                  path_config_source:
                    path: /etc/envoy/config/routes/direct_route.yaml
                    watched_directory:
                      path: /etc/envoy/config/routes
                route_config_name: direct_route

              http_filters:
                - name: envoy.filters.http.local_ratelimit
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                    stat_prefix: http_local_rate_limiter
                    token_bucket:
                      max_tokens: 100
                      tokens_per_fill: 10
                      fill_interval: 10s
                    filter_enabled:
                      runtime_key: local_rate_limit_enabled
                      default_value:
                        numerator: 90
                        denominator: HUNDRED
                    filter_enforced:
                      runtime_key: local_rate_limit_enforced
                      default_value:
                        numerator: 50
                        denominator: HUNDRED

                - name: envoy.filters.http.ext_authz
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                    transport_api_version: V3
                    failure_mode_allow: false
                    clear_route_cache: true
                    grpc_service:
                      envoy_grpc:
                        cluster_name: ext_authz_cluster
                    allowed_headers:
                      patterns:
                        - exact: "x-auth-token"

                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
    name: ws_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10001
    filter_chains:
      - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_ws
              upgrade_configs:
                - upgrade_type: websocket

              rds:
                config_source:
                  resource_api_version: V3
                  path_config_source:
                    path: /etc/envoy/config/routes/direct_route_ws.yaml
                    watched_directory:
                      path: /etc/envoy/config/routes
                route_config_name: direct_route_ws

              http_filters:
                - name: envoy.filters.http.local_ratelimit
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                    stat_prefix: http_local_rate_limiter
                    token_bucket:
                      max_tokens: 100
                      tokens_per_fill: 10
                      fill_interval: 10s
                    filter_enabled:
                      runtime_key: local_rate_limit_enabled
                      default_value:
                        numerator: 90
                        denominator: HUNDRED
                    filter_enforced:
                      runtime_key: local_rate_limit_enforced
                      default_value:
                        numerator: 50
                        denominator: HUNDRED

                - name: envoy.filters.http.ext_authz
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                    transport_api_version: V3
                    failure_mode_allow: false
                    clear_route_cache: true
                    grpc_service:
                      envoy_grpc:
                        cluster_name: ext_authz_cluster
                    allowed_headers:
                      patterns:
                        - exact: "x-auth-token"

                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
    name: tcp_echo_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10002
    filter_chains:
      - filters:
          - name: envoy.filters.network.echo
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.echo.v3.Echo